from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('admin_home', views.admin_home, name='admin_home'),
    path('customer_home', views.customer_home, name='customer_home'),
    path('open_signin', views.open_signin, name='open_signin'),
    path('open_admin_signin', views.open_admin_signin, name='open_admin_signin'),
    path('open_signup', views.open_signup, name='open_signup'),
    path('signup', views.signup, name='signup'),
    path('signin', views.signin, name='signin'),
    path('logout', views.logout, name='logout'),
    path('forgot_password', views.forgot_password, name='forgot_password'),
    path('open_add_restaurant', views.open_add_restaurant, name='open_add_restaurant'),
    path('add_restaurant', views.add_restaurant, name='add_restaurant'),
    path('open_show_restaurant', views.open_show_restaurant, name='open_show_restaurant'),
    path('open_orders', views.open_orders, name='open_orders'),
    path('open_users', views.open_users, name='open_users'),
    path('open_view_user/<int:user_id>', views.open_view_user, name='open_view_user'),
    path('open_update_user/<int:user_id>', views.open_update_user, name='open_update_user'),
    path('update_user/<int:user_id>', views.update_user, name='update_user'),
    path('delete_user/<int:user_id>', views.delete_user, name='delete_user'),
    path('open_update_restaurant/<int:restaurant_id>', views.open_update_restaurant, name='open_update_restaurant'),  
    path('update_restaurant/<int:restaurant_id>', views.update_restaurant, name='update_restaurant'), 
    path('delete_restaurant/<int:restaurant_id>', views.delete_restaurant, name='delete_restaurant'), 
    path('open_update_menu/<int:restaurant_id>', views.open_update_menu, name='open_update_menu'), 
    path('update_menu/<int:restaurant_id>', views.update_menu, name='update_menu'),
    path('update_menu_item/<int:item_id>', views.update_menu_item, name='update_menu_item'),
    path('delete_menu_item/<int:item_id>', views.delete_menu_item, name='delete_menu_item'),
    path('view_menu/<int:restaurant_id>/<str:username>', views.view_menu, name='view_menu'),
    path('add_to_cart_ajax/<int:item_id>/<str:username>/', views.add_to_cart_ajax, name='add_to_cart_ajax'),
    path('remove_from_cart_ajax/<int:item_id>/<str:username>/', views.remove_from_cart_ajax, name='remove_from_cart_ajax'),
    path('cart_count/<str:username>/', views.cart_count, name='cart_count'),
    path('show_cart/<str:username>', views.show_cart, name='show_cart'), 
    path('checkout/<str:username>/', views.checkout, name='checkout'),
    path('orders/<str:username>/', views.orders, name='orders'),
    path('heartbeat/', views.heartbeat, name='heartbeat'),
    path(
    'verify_payment/<str:username>/',
    views.verify_payment,
    name='verify_payment'
),

]